global:
  resolve_timeout: 1m

route:
  receiver: "jenkins-rollback-webhook"
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m

receivers:
  - name: "jenkins-rollback-webhook"
    webhook_configs:
      - url: "http://54.209.155.223:8080/generic-webhook-trigger/invoke?token=ROLLBACK_BAF692_TOKEN"
        send_resolved: false
        http_config:
          basic_auth:
            # Replace with your Jenkins username + API token
            username: "Muhammad_Haseeb"
            password: '11bdf7627f398a75a0400e106cda3b87b5'
